FROM nvcr.io/nvidia/tritonserver:23.10-py3

COPY ./inference/requirements.txt /opt/tritonserver/requirements.txt
RUN pip install --upgrade pip && pip install -r /opt/tritonserver/requirements.txt

CMD ["tritonserver", "--model-repository=/models"]
