FROM nvcr.io/nvidia/tritonserver:23.10-py3

COPY ./inference/requirements.txt /opt/tritonserver/requirements.txt
RUN pip install --upgrade pip && pip install -r /opt/tritonserver/requirements.txt

ENV LOG_VERBOSE ${LOG_VERBOSE}
CMD ["sh", "-c", "tritonserver --model-repository=/models --log-verbose=$LOG_VERBOSE"]
